version: "3.3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: WycieczkiDatabase
    networks:
      - wp_network
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - wp_network
    ports:
      - 8081:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql:3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ""
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - ./wp-content/themes/:/var/www/html/wp-content/themes/
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: WycieczkiDatabase
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
    networks: 
      - wp_network
networks:
  wp_network:
    external: false